package eu.glomicave.persistence;

public enum PredefinedRelations {
	IS, REL_INSTANCE_OF, ADJECTIVE_OF, JOIN, AND, HAVE_ON, HAVE_OF, CONTAINS, 
	IS_PART_OF_SENTENCE, IS_PART_OF_PATHWAY, HAS_LF, APPEARS_IN, APPEARS_IN_LOWERCASE, FACT_APPEARS_IN, SYNONYM_WITH,
	MAKES_PREDICTION, TARGET, INPUT, COOCCURS_WITH, HAS_FACT, HAS_POLARITY, HAS_MODALITY,HAS_ATTRIBUTION, OIE_RELATED_WITH;
}
