package eu.glomicave.persistence;

public enum PredefinedCategories {

	CONCEPT, NAMED_ENTITY, PUBLICATION, SENTENCE, RELATION_NODE, ADJ_NOUN, PATHWAY, PREDICTOR, PREDICTION,
	METABOLITE, GENE, GENE_PRODUCT, PROTEIN, TRAIT, LEXICAL_FORM, FACT, POLARITY, MODALITY, ATTRIBUTION;
}
